<a href="https://colab.research.google.com/github/MrLuciferM/DataScience_salary_proj/blob/master/DataWrangling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [28]:
path = 'https://raw.githubusercontent.com/PlayingNumbers/ds_salary_proj/data_cleaning/glassdoor_jobs.csv'

In [29]:
df = pd.read_csv(path)
df

     Unnamed: 0  ...                                        Competitors
0             0  ...                                                 -1
1             1  ...                                                 -1
2             2  ...                                                 -1
3             3  ...  Oak Ridge National Laboratory, National Renewa...
4             4  ...               Commerce Signals, Cardlytics, Yodlee
..          ...  ...                                                ...
951         951  ...                    See Tickets, TicketWeb, Vendini
952         952  ...                                                 -1
953         953  ...                                                 -1
954         954  ...                                             Slalom
955         955  ...                                                 -1

[956 rows x 15 columns]

In [30]:
df_cleaned = df[df['Salary Estimate'] != '-1']
df_cleaned

     Unnamed: 0  ...                                        Competitors
0             0  ...                                                 -1
1             1  ...                                                 -1
2             2  ...                                                 -1
3             3  ...  Oak Ridge National Laboratory, National Renewa...
4             4  ...               Commerce Signals, Cardlytics, Yodlee
..          ...  ...                                                ...
950         950  ...                         Pfizer, AstraZeneca, Merck
951         951  ...                    See Tickets, TicketWeb, Vendini
952         952  ...                                                 -1
953         953  ...                                                 -1
955         955  ...                                                 -1

[742 rows x 15 columns]